### PR TITLE
Core/Build: Fix finding openssl 1.1 and fix windows build for recent OpenSSL versions

### PR DESCRIPTION
**Pull request by Nightprince**
…OpenSSL versions

### CODE REVIEW

**Comment by AriDEV** [comment]
MT libraries link static, MD libraries link dynamic.

CMAKE_SIZEOF_VOID_P is bad to check for archetype. example AMD FX-4100 is void pointer 4 but x64.

your commit basicaly reverts my changes from jun 2018.

**Comment by Nightprince** [comment]
But it's not currently available in Windows and can't find openssl

**Comment by AriDEV** [comment]
for windows you need 64 bit openssl libraries. so adding 32 bit version is pointless.

**Comment by Nightprince** [comment]
but in new version of openssl , save in program files

https://www.yekta-upload.ir/uploads/f180e1b323bc1.jpg

**Comment by AriDEV** [comment]
image

**Comment by AriDEV** [comment]
Did you downloaded the installer from the wiki?

**Comment by Nightprince** [comment]
https://slproweb.com/products/Win32OpenSSL.html

**Comment by AriDEV** [comment]
Do not install light version, read the wiki.

**Comment by Nightprince** [comment]
But the version of openssl in in my photo is not Light

**Comment by AriDEV** [comment]
It must be, Light version default path is /program files/ if we would add /program files/ people would have issues cause they download light version.

**Comment by Nightprince** [comment]
Ok , I'll download it again and check it out.

You also said that SkyFire could not compile with Visual Studio 2015, but I compiled it.

**Comment by AriDEV** [comment]
pm me in discord and i will explain.

**Comment by Nightprince** [comment]
yes, it's true.

> It must be, Light version default path is /program files/ if we would add /program files/ people would have issues cause they download light version.

yes, it's true. sorry

**Pull request closed without merging**
