### PR TITLE
Core/Scripts: npc_skorn_whitecloud gossip moved to DB

### PR DESCRIPTION
**Pull request by Nightprince**

### CODE REVIEW

**Comment by Nightprince** [comment]
@AriDEV why closed ?

**Comment by AriDEV** [comment]
the whole script can be moved to db no reason to convert just half of it, not even sure if the script is actualy needed could be easy done with conditions

**Comment by Nightprince** [comment]
> 
> 
> the whole script can be moved to db no reason to convert just half of it, not even sure if the script is actualy needed could be easy done with conditions

What your problem ?

Texts should be read from database rather than written into script.
This should be done to reduce size of core and improve performance, no problems.
Do you close it without testing it? it is interesting.

**Comment by Nightprince** [comment]
Merge this. i want commit new fix in this file.

**Pull request closed without merging**
