### PR TITLE
Core/Maps: Activate creatures and objects during opening cinematics and other flyby cameras.

### PR DESCRIPTION
**Pull request by Nightprince**
Requires re-running map extractor to extract camera m2 files from data

### CODE REVIEW

**Comment by SkyFire** [comment]
Doesn't seem to extract all the camera files.

**Comment by Nightprince** [comment]
> Doesn't seem to extract all the camera files.

Which does not extract?
Does your game have such data and is it complete?
You should have 27 camera files:

- abyssal_maw_camerafly_01.m2
- firelands_bridge_camera_01.m2
- flyby_maelstrom.m2
- flyby_mogubridge_collapse.m2
- flyby_mogubridge_collapse02.m2
- flyby_mogusecret_door.m2
- flyby_mogusecret_door02.m2
- FlyByBloodElf.m2
- FlyByDeathKnight.m2
- FlybyDraenei.m2
- flybydwarf.m2
- flybygateofthesettingsun.m2
- flybygilneas_telescope.m2
- flybygilneasshort.m2
- flybygnome.m2
- flybygoblin.m2
- flybyhuman.m2
- flybynightelf.m2
- flybyorc.m2
- flybypandaren.m2
- FlyBySunwell5Man.m2
- flybytauren.m2
- flybytroll.m2
- flybyundead.m2
- flybyworgen.m2
- palantirofazora.m2
- scry_cam.m2

**Comment by Nightprince** [comment]
expansion1.mpq:

- FlyByBloodElf.m2
- FlybyDraenei.m2
- FlyBySunwell5Man.m2

expansion2.mpq:

- FlyByDeathKnight.m2

model.mpq:

- abyssal_maw_camerafly_01.m2
- firelands_bridge_camera_01.m2
- flyby_maelstrom.m2
- flybydwarf.m2
- flybygateofthesettingsun.m2
- flybygilneas_telescope.m2
- flybygilneasshort.m2
- flybygnome.m2
- flybygoblin.m2
- flybyhuman.m2
- flybynightelf.m2
- flybyorc.m2
- flybypandaren.m2
- flybytauren.m2
- flybytroll.m2
- flybyundead.m2
- flybyworgen.m2
- palantirofazora.m2
- scry_cam.m2

wow-update-base-16516.mpq:

- flyby_mogubridge_collapse.m2
- flyby_mogubridge_collapse02.m2
- flyby_mogusecret_door.m2
- flyby_mogusecret_door02.m2

**Comment by SkyFire** [comment]
Only extracts 8

**Pull request merged**
